<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1vurjG\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1vurjG/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL1vurjG.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL1vurjG\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerL1vurjG\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'L1vurjG',
    'container.build_id' => 'dfb02393',
    'container.build_time' => 1650506681,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1vurjG');
