<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSfxxmAL\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSfxxmAL/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSfxxmAL.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSfxxmAL\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerSfxxmAL\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'SfxxmAL',
    'container.build_id' => '488ef65f',
    'container.build_time' => 1650437471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSfxxmAL');
